config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  constraints(subdomain: ['patwalls', 'leeronisrael']) do
    root "i/posts#index", as: 'subdomain_blog_index'
    get '/:post_id', to: 'i/posts#show', as: 'subdomain_blog_show'
  end

  constraints(host: ['patwalls.co', 'leeronisrael.com']) do
    root "i/posts#index", as: 'host_blog_index'
    get '/:post_id', to: 'i/posts#show', as: 'host_blog_show'
  end

  root 'welcome#index'
  get "/open", to: "welcome#open"

  resource :profile, only: [:show], controller: 'profile'
  resource :dashboard, only: [:show], controller: 'dashboard', :as => 'user_root'

  resources :posts do
    post :publish
    post :unpublish
  end

  resources :users, only: [:update]

  get '/google_drive_authorize' => 'google_drive#authorize', as: 'google_drive_authorize'
  get '/callback' => 'google_drive#callback', as: 'callback'
  get '/privacy_policy' => 'privacy_policy#show'
  get '/waitlist' => 'waitlist#show'

  get '/:username', to: 'i/posts#index', as: 'blog_index'
  get '/:username/:post_id', to: 'i/posts#show', as: 'blog_show'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def show
    return redirect_to google_drive_authorize_path if current_user.google_auth_token.nil?
    return redirect_to "/#{current_user.username}"
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/show.html.haml
.page
  .content
    .dashboard
      %h4 My posts
      .buttons
        = link_to("Edit Profile", profile_path, class: "btn btn-secondary")
        = link_to("➕ New Blog Post", posts_path, method: :post, class: "btn btn-primary")
    .posts
      %ul.list-unstyled
        - if @posts.none?
          Looks like you haven't created a post yet. Click the blue button over there 👉
        - @posts.each do |post|
          - state = post.is_published? ? "Published" : "Draft"
          %li.media
            .media-body
              %h5.mt-0.mb-1= "#{post.title} (#{state})"
              %ul
                %li= link_to "Google Doc", "https://docs.google.com/document/d/#{post.google_doc}/edit"
                %li= link_to "View Blog Post", "#{current_user.username}/#{post.slug}"
                %li= link_to "Edit Post / Publish", edit_post_path(post)
                %li= link_to "Delete Post", post_path(post), method: :delete