config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  constraints(subdomain: ['patwalls', 'leeronisrael']) do
    root "i/posts#index", as: 'subdomain_blog_index'
    get '/:post_id', to: 'i/posts#show', as: 'subdomain_blog_show'
  end

  constraints(host: ['patwalls.co', 'leeronisrael.com']) do
    root "i/posts#index", as: 'host_blog_index'
    get '/:post_id', to: 'i/posts#show', as: 'host_blog_show'
  end

  root 'welcome#index'
  get "/open", to: "welcome#open"

  resource :profile, only: [:show], controller: 'profile'
  resource :dashboard, only: [:show], controller: 'dashboard', :as => 'user_root'

  resources :posts do
    post :publish
    post :unpublish
  end

  resources :users, only: [:update]

  get '/google_drive_authorize' => 'google_drive#authorize', as: 'google_drive_authorize'
  get '/callback' => 'google_drive#callback', as: 'callback'
  get '/privacy_policy' => 'privacy_policy#show'
  get '/waitlist' => 'waitlist#show'

  get '/:username', to: 'i/posts#index', as: 'blog_index'
  get '/:username/:post_id', to: 'i/posts#show', as: 'blog_show'
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user

  has_attached_file :meta, styles: { medium: "300x300>", thumb: "100x100>" }, s3_protocol: :https
  validates_attachment_content_type :meta, content_type: /\Aimage\/.*\z/

  scope :published, -> { where(is_published: true) }
  scope :draft, -> { where(is_published: false) }
  scope :most_recent_first, -> { order(published: :desc) }

  def should_generate_new_friendly_id?
    (slug.blank? || self.title_changed?) && !self.is_published
  end
end

app/controllers/i/posts_controller.rb
class I::PostsController < ApplicationController
  def index
    logger.debug "---------"
    logger.debug "---------"
    logger.debug request.host
    logger.debug "---------"
    logger.debug "---------"

    redirect_to google_drive_authorize_path if current_user && current_user.google_auth_token.nil?
    
    @user = User.find_by(username: host_or_param)
    return redirect_to root_path unless @user

    if params[:drafts]
      @posts = @user.posts.draft.most_recent_first
    else
      @posts = @user.posts.published.most_recent_first
    end
  end

  def show
    @user = User.find_by(username: host_or_param)
    return redirect_to root_path unless @user

    @post = @user.posts.friendly.find(params[:post_id])
    html = GoogleDrive.new(@user).get_html(@post)
    @parsed = Nokogiri::HTML::DocumentFragment.parse(html).to_html
    to_parse = Nokogiri::HTML(@parsed)
    @parsed = parse_links(to_parse)
    @text_of_post = helpers.truncate(helpers.strip_tags(to_parse.to_s), length: 290)
    @first_img_path = to_parse.xpath('//img')&.first&.attr('src')
  end

  private

  def subdomain_or_param
    (request.subdomain.present? && request.subdomain != "www") ? request.subdomain : params[:username]
  end

  def host_or_param
    (request.host.present? && request.host != "localhost" && request.host != "youdontneedwp.com" && request.host != "www.youdontneedwp.com") ? User::DOMAIN_MAPPING[request.host] : params[:username]
  end

  def parse_links(doc)
    doc.css('a').each do |link|
      link['href'] = strip_google_link(link['href'])
    end
    doc.to_s
  end

  def strip_google_link(href)
    return href if href.nil?
    return href if href.include?("mailto")
    return href if !href.include?('url?q=')

    stripped_link = href.split('url?q=')[1].split('&sa=')[0]
  end
end

app/controllers/posts_controller.rb
require "open-uri"

class PostsController < ApplicationController
  before_action :authenticate_user!

  def create
    file = GoogleDrive.new(current_user).create_file!

    post = current_user.posts.create(
      title: "My new post.",
      google_doc: file.id,
      published: Date.today
    )

    redirect_to edit_post_path(post, doc: true)
  end

  def show
    @post = Post.friendly.find(params[:id])
  end

  def edit
    @post = Post.friendly.find(params[:id])
  end

  def update
    @post = Post.friendly.find(params[:id])

    html = GoogleDrive.new(current_user).get_html(@post)
    @parsed = Nokogiri::HTML::DocumentFragment.parse(html).to_html
    to_parse = Nokogiri::HTML(@parsed)
    @first_img_path = to_parse.xpath('//img')&.first&.attr('src')

    if @first_img_path
      @post.update(meta: open(@first_img_path))
    end

    if @post.update(post_params)
      flash[:success] = "Post updated!"
      redirect_to edit_post_path(@post.id)
    else
      flash[:error] = "something went wrong"
      redirect_to edit_post_path(@post.id)
    end
  end

  def destroy
    @post = Post.friendly.find(params[:id])

    if @post.destroy!
      flash[:success] = "Post updated!"
      redirect_to user_root_path
    else
      flash[:error] = "something went wrong"
      redirect_to user_root_path
    end
  end

  def publish
    @post = Post.friendly.find(params[:post_id])

    if @post.update!(is_published: true)
      flash[:success] = "Post published!"
      redirect_to user_root_path
    else
      flash[:error] = "something went wrong"
      redirect_to user_root_path
    end
  end

  def unpublish
    @post = Post.friendly.find(params[:post_id])

    if @post.update!(is_published: false)
      flash[:success] = "Post unpublished."
      redirect_to user_root_path
    else
      flash[:error] = "something went wrong"
      redirect_to user_root_path
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :published, :is_published)
  end
end

app/helpers/i/posts_helper.rb
module I::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.haml
:ruby
  set_meta_tags(title: "Editing #{@post.title}")

.page.edit
  .upper-nav
    .nav-left
      = form_tag(post_path(@post), method: "PATCH") do
        .input-group
          .input-group-prepend
            %span.input-group-text Title
          = text_field(:post, :title, class: "form-control title", placeholder: "Title")
          .input-group-prepend
            %span.input-group-text Publish Date
          = date_field(:post, :published, class: "form-control date", placeholder: "Published Date")
          = submit_tag("Update", class: "btn btn-primary")
    .nav-right
      .dropdown
        %a#dropdownMenuLink.btn.btn-secondary.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          Options
        .dropdown-menu{"aria-labelledby" => "dropdownMenuLink"}
          = link_to "View Draft", "/#{current_user.username}/#{@post.slug}", target: "_blank", class: "dropdown-item"
          = link_to "Pop Out Google Doc", "https://docs.google.com/document/d/#{@post.google_doc}/edit", target: "_blank", class: "dropdown-item"
      - if @post.is_published
        = link_to "Unpublish", post_unpublish_path(@post.id), method: :post, class: 'btn btn-primary publish'
      - else
        = link_to "Publish", post_publish_path(@post.id), method: :post, class: 'btn btn-primary publish'
  .gdoc-editor
    %iframe{:src => "https://docs.google.com/document/d/#{@post.google_doc}/edit"}

app/views/posts/show.html.haml
%h1 This is a post!

= link_to "Edit Post", edit_post_path(@post)

= link_to "Delete Post", post_path(@post), method: :delete

= link_to "Google Doc", "https://docs.google.com/document/d/#{@post.google_doc}/edit"