config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  constraints(subdomain: ['patwalls', 'leeronisrael']) do
    root "i/posts#index", as: 'subdomain_blog_index'
    get '/:post_id', to: 'i/posts#show', as: 'subdomain_blog_show'
  end

  constraints(host: ['patwalls.co', 'leeronisrael.com']) do
    root "i/posts#index", as: 'host_blog_index'
    get '/:post_id', to: 'i/posts#show', as: 'host_blog_show'
  end

  root 'welcome#index'
  get "/open", to: "welcome#open"

  resource :profile, only: [:show], controller: 'profile'
  resource :dashboard, only: [:show], controller: 'dashboard', :as => 'user_root'

  resources :posts do
    post :publish
    post :unpublish
  end

  resources :users, only: [:update]

  get '/google_drive_authorize' => 'google_drive#authorize', as: 'google_drive_authorize'
  get '/callback' => 'google_drive#callback', as: 'callback'
  get '/privacy_policy' => 'privacy_policy#show'
  get '/waitlist' => 'waitlist#show'

  get '/:username', to: 'i/posts#index', as: 'blog_index'
  get '/:username/:post_id', to: 'i/posts#show', as: 'blog_show'
end

app/views/layouts/_footer.html.haml
%script{:async => "", :charset => "utf-8", :src => "https://platform.twitter.com/widgets.js"}

%footer.footer
  = link_to("YDNW", root_path)
  = link_to("Contact Us", "mailto:patrickswalls@gmail.com")
  .div
    I created this on a
    = link_to("24 hour live stream!", "https://twitter.com/thepatwalls/status/1043242997050167302")
    %a.twitter-follow-button{"data-show-count" => "false", :href => "https://twitter.com/thepatwalls?ref_src=twsrc%5Etfw"} Follow @thepatwalls

app/views/layouts/_header.html.haml
- logo_path = current_user ? user_root_path : "https://youdontneedwp.com"

%header.header
  .container-lrg.header
    .flex.col-12.spread
      = link_to("Create A Blog With Google Docs", logo_path)
      - if current_user
        .links
          = link_to("My Blog", "/#{current_user.username}")
          = link_to("Sign Out", destroy_user_session_path, method: :delete)
      - else
        = link_to("Sign In", new_user_session_url)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport" }/
    %meta{ name: "google-site-verification", content: "M-Hm1or75hJNqJOAuz6s_JYmY_AoKYR1gtnXlIdV7fw"}/
    = display_meta_tags
    %title Ydnw
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    - if content_for? :customized_emoji
      = yield :customized_emoji
    - else
      %link{:href => "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/apple/155/writing-hand_270d.png", :rel => "icon"}
    - if current_user
      :javascript
        (function(d, h, m){
            var js, fjs = d.getElementsByTagName(h)[0];
            if (d.getElementById(m)){return;}
            js = d.createElement(h); js.id = m;
            js.onload = function(){
                window.makerWidgetComInit({
                position: "left",
                widget: "jriplihz6ik21iik-yo8oekcx9p47oc0q-j32rpsdvj6msgsol"
            })};
            js.src = "https://makerwidget.com/js/embed.js";
            fjs.parentNode.insertBefore(js, fjs)
        }(document, "script", "dhm"))
    - if Rails.env.production?
      %script{:async => "", :src => "https://www.googletagmanager.com/gtag/js?id=UA-75503228-5"}
      :javascript
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-75503228-5');

  %body
    .font-modern
      .gray-black
        = render "layouts/header"
        - flash.each do |key, value|
          = content_tag :div, value, class: "alert alert-info"
        .midsection{ style: "min-height:80vh;"}
          = yield
        -# = render "layouts/footer"